fix parsing

diff --git a/bin/gtfcr-init b/bin/gtfcr-init
--- a/bin/gtfcr-init
+++ b/bin/gtfcr-init
@@ -3,29 +3,27 @@
 # gtfc init
 
 gitcluster_init() {
-  PEERPORT="22"
+  MYUSER1="urep"
+  PEERPORT1="22"
   TOSPLIT=$1
-  if [ "x" != "x${TOSPLIT%@*}" ]; then
-    MYUSER="${TOSPLIT%@*}"
-  fi
-  HOSTANDPORT="${TOSPLIT#*@}"
-  if [ "x" != "x${HOSTANDPORT}" ]; then
-    HOST="${HOSTANDPORT%:*}"
-    PEERPORT="${HOSTANDPORT#*:}"
-  fi
-  first=$1
   repo=$2
-
-  if [ "x" = "x$first" ]; then
-    echo "ERROR: missing arg" >&2
+  if [ "x" != "x${TOSPLIT%@*}" ]; then
+    MYUSER1="${TOSPLIT%@*}"
+  fi
+  HOSTANDPORT1="${TOSPLIT#*@}"
+  if [ "x" != "x${HOSTANDPORT1%:*}" ]; then
+         HOST1="${HOSTANDPORT1%:*}"
+  fi
+  if [ "x" != "${HOSTANDPORT1#*:}" ]; then
+    PEERPORT1="${HOSTANDPORT1#*:}"
+  fi
+  if [ "x" = "x$HOST1" ]; then
+    echo "ERROR: missing host" >&2
     exit 1
-
-
-
   elif [ "x" = "x$repo" ]; then
     repo="gitsync"
   fi
-  ssh -t -p $PEERPORT urep@$HOST gtfc init $first $repo
+  ssh -t -p $PEERPORT1 $MYUSER1@$HOST1 gtfc init $1 $repo
 
 }
 
