fix host1

diff --git a/bin/gtfcr-init b/bin/gtfcr-init
--- a/bin/gtfcr-init
+++ b/bin/gtfcr-init
@@ -12,13 +12,13 @@ gitcluster_init() {
   fi
   HOSTANDPORT1="${TOSPLIT#*@}"
   if [ "x" != "x${HOSTANDPORT1%:*}" ]; then
-         HOST1="${HOSTANDPORT1%:*}"
+    HOST1="${HOSTANDPORT1%:*}"
   fi
   if [ "x" != "${HOSTANDPORT1#*:}" ]; then
     PEERPORT1="${HOSTANDPORT1#*:}"
   fi
   if [ "x" = "x$HOST1" ]; then
-    echo "ERROR: missing host" >&2
+    echo "ERROR: missing host1" >&2
     exit 1
   elif [ "x" = "x$repo" ]; then
     repo="gitsync"
